apiVersion: apps/v1
kind: Deployment
metadata:
  name: api
  namespace: quiz-app
  labels:
    role: api
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: api
  template:
    metadata:
      labels:
        role: api
    spec:
      containers:
        - name: api
          image: suryaprasad9773/backend:06215faef1a83bf831e5f90d46a77f2f156ac3b8
          imagePullPolicy: IfNotPresent 
          env:
            - name: MONGO_CONN_STR
              value: mongodb://mongodb-svc:27017/quiz_database?directConnection=true
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: mongodb-secret
                  key: mongo-secret-key     
          ports:
            - containerPort: 8080
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 2
            periodSeconds: 5
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 5
            successThreshold: 1
