apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: quiz-app
  labels:
    role: frontend
    env: demo
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: suryaprasad9773/frontend:06215faef1a83bf831e5f90d46a77f2f156ac3b8
        ports:
        - containerPort: 80
